# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    name = "People"
    identifier = "people"
    url = "/pages/people/"
    weight = 2

[[main]]
    name = "Current Members"
    parent = "people"
    url = "/pages/currentmembers/"
    weight = 1

[[main]]
    name = "Former Members"
    parent = "people"
    url = "/pages/formermembers/"
    weight = 2

[[main]]
    name = "Current Projects"
    identifier = "projects"
    url = "#projects"
    weight = 3

[[main]]
    name = "Publications"
    identifier = "publications"
    url = "#publications"
    weight = 4

[[main]]
    name = "Resources"
    identifier = "resources"
    url = "/pages/resources/"
    weight = 5

[[main]]
    name = "Opportunities"
    url = "/pages/opportunities/"
    weight = 6

[[main]]
    name = "Affiliations"
    url = "/pages/affiliations/"
    weight = 7


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
